const types = {
    FETCH_ALL_COLLECTIONS: "FETCH_ALL_COLLETIONS",
    FETCH_LISTINGS: "FETCH_LISTINGS",
    FETCH_SELECTED_COLLECTION_INFO: "FETCH_SELECTED_COLLECTION_INFO",
    CURRENT_COLLECTION_LOADING_DONE : "CURRENT_COLLECTION_LOADING_DONE",
    SORT_BY: "SORT_BY",
    CHANGE_PAGE: "CHANGE_PAGE",
    SELECT_COLLECTION: "SELECT_COLLECTION",
    SET_WALLET_BALANCE: "SET_WALLET_BALANCE",
    AUTO_BUY_STATE: "AUTO_BUY_STATE",

    ADD_BASKET: "ADD_BASKET",
    REMOVE_BASKET_ITEM: "REMOVE_BASKET_ITEM",
    LOADING_DONE: "LOADING_DONE",
    UPDATE_BASKET_ITEM: "UPDATE_BASKET_ITEM",
    EMPTY_BASKET: "EMPTY_BASKET"
}

export default types;
